version: "3.7"
services:
  janus:
    image: stably/janus:latest
    container_name: janus_testnet
    ports:
    # - "23890:23889"
      - "3889:3889"
    environment:
      #- QTUM_RPC=http://stably:mandatorypassword@qtum:23890
      - QTUM_NETWORK=testnet
    depends_on:
      - qtum
    command: --bind 0.0.0.0 -v `pwd`:/dapp
  qtum:
    image: qtum/qtum:latest
    container_name: qtum_testnet
    ports:
      - "3889:3889"
    command: qtumd -testnet=1 -rpcbind=0.0.0.0:3889 -rpcallowip=0.0.0.0/0 -rpcuser=qtum -rpcpassword=qtum -printtoconsole -logevents
    
