version: "3.7"
services:
  janus:
    image: stably/janus:latest
    container_name: janus_testnet
    ports:
      - "23890:23889"
    environment:
      - QTUM_RPC=http://stably:mandatorypassword@qtum:3889
    depends_on:
      - qtum
    command: --bind 0.0.0.0
  qtum:
    image: qtum/qtum:latest
    container_name: qtum_testnet
    ports:
      - "3890:3889"
    command: qtumd -testnet=1 -rpcbind=0.0.0.0:3889 -rpcallowip=0.0.0.0/0 -rpcuser=stably -rpcpassword=mandatorypassword -printtoconsole
    volumes:
      - /data/qtum-data/:/root/.qtum/
